version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myob-ops-technical-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xdepxnywlj4o"
s3_prefix = "myob-ops-technical-test"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
